FROM domistyle/idrac6

MAINTAINER zhangdahai

RUN apt-get update && \
apt-get install -y vim net-tools && \
apt-get install -y icedtea-netx && \
apt-get install -y curl

COPY startup.inspur.4.40.sh /startapp.sh
